spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create

# postgresql://postgres:sZQAFgpTIQlCYlMeCXqTllBoTLHIgtsS@metro.proxy.rlwy.net:17263/railway